### PR TITLE
Add support of point data

### PR DESCRIPTION
**Pull request by sebhahn**
Support point data according to CF convention. Only works once the pull request TUW-GEO/pygeobase/pull/25 of pygeobase has been merged (otherwise lon, lat information is missing).

### CODE REVIEW

**Comment by cpaulik** [comment]
Could you fix Python 3 support?

**Comment by sebhahn** [comment]
yes, I wasn't aware of the fact that `iteritems` was removed in python 3

**Comment by cpaulik** [comment]
Also `itervalues` was removed.

**Comment by sebhahn** [comment]
I see, learned something today.

**Comment by cpaulik** [comment]
That looks cool. Could you add it to the changelog?

**Comment by sebhahn** [comment]
done. I have to say that we are not really consistent about the change log style and file type.

**Pull request merged**
