### PR TITLE
Update netcdf4 requirement to v1.4.2

### PR DESCRIPTION
**Pull request by sebhahn**

### CODE REVIEW

**Comment by sebhahn** [comment]
@cpaulik are you happy raising the requirement of netcdf4? All tests are working fine.

Should we add a test for the initial problem you mentioned [here](https://github.com/Unidata/netcdf4-python/issues/784)?

**Comment by cpaulik** [comment]
Yes, fine with me. 

Is `1.4.2` necessary or can we be a little less strict?

The tests should fail if the issue comes back. At least they did in the past.

**Comment by cpaulik** [comment]
Ok. Then let's at least do something like `>=1.4.2,<=1.2.8` so we don't force people to upgrade.

**Comment by sebhahn** [comment]
@cpaulik somehow pip is not able to figure out the right version using `>=1.4.2,<=1.2.8`, is it ok if we stick with `>=1.4.2`?

**Comment by cpaulik** [comment]
Ok. I've also reported this, might be a bug in pip https://github.com/pypa/pip/issues/6034

**Comment by cpaulik** [comment]
So this seems to not be possible. 

We could still do something like `netcdf4!=1.2.9, !=1.3.0, !=1.3.1, !=1.4.0, !=1.4.1` but that is probably not worth it.

**Comment by cpaulik** [comment]
Do you want to update this back to the way it was before so that we can merge it?

**Comment by cpaulik** [comment]
No problem. I've run into this issue today so that's why I thought about it.

**Pull request merged**
